# 站点基础信息
site_name: F0ne's Docs              # 网站标题（显示在浏览器标签页 & 左上角）
site_description: 这是一个网络安全知识库。  # 网站描述（SEO 用）
site_url: https://f0nesec.github.io/f0nesec-docs/       # 站点正式访问地址（GitHub Pages 必填）

# GitHub 仓库相关（右上角图标）
repo_name: f0nesec/f0nesec-docs   # 图标旁显示的文字
repo_url: https://github.com/f0nesec/f0nesec-docs   # 仓库地址（右上角跳转）
edit_uri: blob/main/docs/ # 编辑代码

# 页脚版权信息
# copyright: Copyright &copy; 2026 Martin Donath

# 额外配置
extra:
  generator: true   # 关闭、开启页脚的 “Made with Material for MkDocs”

# Markdown 功能扩展
markdown_extensions:

  # 目录 / 锚点
  - toc:
      permalink: true # 每个标题右侧生成一个 ¶ 图标

  # 提示框
  - admonition  # 启用 !!! note / warning / tip / danger 等提示块

  - pymdownx.details  # 允许提示框折叠（??? note）

  # 代码块增强
  - pymdownx.superfences  # 允许：提示框里嵌套代码，Mermaid / 多语言代码块

  - pymdownx.highlight:
      linenums: true            # 显示代码行号（核心）
      anchor_linenums: true     # 行号可点击（生成锚点）
      line_spans: __span        # Material 推荐配置（用于高亮/复制）
      pygments_lang_class: true # 给代码块加 language-xxx 类名
      auto_title: true          # 自动显示代码框类型，不定义需要通过 tilte=""指定

  - pymdownx.inlinehilite # 支持行内代码高亮：`==highlight==`

  - pymdownx.keys # 支持快捷键样式：++ctrl+alt+del++

  - pymdownx.snippets # 支持从外部文件插入代码，例如：--8<-- "code/example.py"

# 主题配置（Material）
theme:
  name: material          # 使用 Material for MkDocs
  language: zh            # 界面语言为中文
  icon:
    repo: fontawesome/brands/git-alt # 使用 FontAwesome 的 GitHub 图标
  # 主题功能
  features:
    - content.code.copy     # 代码块右上角「复制按钮」
    - content.code.select   # 代码块支持鼠标拖拽选择
    - navigation.top        # 滚动后显示返回顶部按钮
    - search.suggest        # 搜索联想
    - search.highlight      # 搜索结果高亮
    - search.share          # 搜索结果可分享链接
    - content.action.edit   # 开启查看源码
    - content.action.view   # 开启编辑源码操作

  # 颜色方案
  palette:
    # 默认深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black       # 顶部导航栏主色
      accent: deep orange   # 链接 / 按钮 / 高亮色
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换浅色模式

    # 可切换的浅色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: 切换深色模式

    # 自动切换，根据系统主题自动切换
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 自动

  # 图标
  favicon: assets/title.png   # 浏览器标签页小图标
  logo: assets/logo.png       # 左上角站点 Logo

# 配置插件
plugins:
  # 显示更新创建日期
  - git-revision-date-localized:
      fallback_to_build_date: true  # 设置文档修改日期
      # enable_creation_date: true  # 设置文档创建日志
  # 显示作者的头像
  - git-committers:
      repository: f0nesec/f0nesec-docs
      branch: main
  # 采用压缩和转换技术优化网站
  - optimize

# 社交链接
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/f0nesec
      name: Github
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/MWKGN3AqG
      name: Discord

# 配置目录结构
nav:
  - 首页: index.md
  - Web 应用程序安全:
      - 概述: Web-Application-Security/index.md
  - 活动目录安全（域控）:
      - 概述: Active-Directory-Security/index.md
  - 移动应用程序安全:
      - 概述: Mobile-Application-Security/index.md
  - 本地权限提升:
      - 概述: Local-Privilege-Escalation/index.md
      - Windows 本地权限提升:
          - 概述: Local-Privilege-Escalation/Windows/index.md
      - Linux 本地权限提升:
          - 概述: Local-Privilege-Escalation/Linux/index.md
  - 横向移动:
    - 概述: Lateral-Movement/index.md
  - 凭证攻击:
    - 概述: Credential-Attacks/index.md
  - 代码审计:
      - 概述: Code-Audit/index.md
  - 检测与规避技术:
      - 概述: Detection-Evasion/index.md
  - 考试与认证专题:
      - 概述: Certifications/index.md
      - OSCP 认证:
        - Certifications/OSCP/index.md
      - OSWE 认证:
        - Certifications/OSWE/index.md
      - OSEP 认证:
        - Certifications/OSEP/index.md
      - OSED 认证:
        - Certifications/OSED/index.md

